<table cellspacing="1" cellpadding="0" class="menu-top"><tr><td>
  <table cellspacing=0 cellpadding=1 width=100%>

    <tr><td valign="middle" class="menu-hdr">motifGPU</td></tr>

    <tr><td class=menus>
      &nbsp;<a class="menus" href="index.shtml">Home</a>
    </td></tr>
    <tr><td class="menus-spacer">&nbsp;-----------------------------------------------</td></tr>
    <tr><td class="menus">
      &nbsp;<a class=menus href="getProg.shtml">Download progam</a>
    </td></tr>
    <tr><td class="menus-spacer">&nbsp;-----------------------------------------------</td></tr>
    <tr><td class="menus">
      &nbsp;<a class=menus href="documents.shtml">Documentation</a>
    </td></tr>
    <tr><td class="menus-spacer">&nbsp;-----------------------------------------------</td></tr>
     <tr><td class="menus">
      &nbsp;<a class=menus href="update.txt">Update & Bug Log</a>
    </td></tr> 
    <tr><td class="menus-spacer">&nbsp;-----------------------------------------------</td></tr>
    <tr><td class="menus">
      &nbsp;<a class="menus" href="contact.shtml">Contact us</a>
    </td></tr>
  </table>
</td></tr></table><br>
